POST http://localhost:4100/users
Content-Type: application/json

{
 "name": "Jackson",
  "email": "admin@gmail.com",
  "nationalId": "190trfffyt8231",
  "phoneNumber": "3-306-78090",
  "location": "City, Country",
  "gender": "Male",
  "nationality": "Country",
  "occupation": "Developer",
  "dateOfBirth": "1990-01-01T00:00:00.000Z",
  "password": "qwerty"
}


### get all user

GET http://localhost:4100/users
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2NlZGI5ZDMtNTFhOS00ZjY2LWFmZWUtM2VjYmY4MjE3MTMzIiwibmFtZSI6IkphY2tzb24gaXNhIiwiZW1haWwiOiJpdHMuamFja3Nvbm13YWRpYTAwMUBnbWFpbC5jb20iLCJuYXRpb25hbElkIjoiMTkwNDczMzkiLCJwaG9uZU51bWJlciI6IjEzMjgtMzA2LTc4MDkwIiwiZGF0ZU9mQmlydGgiOiIxOTkwLTAxLTAxVDAwOjAwOjAwLjAwMFoiLCJnZW5kZXIiOiJNYWxlIiwibmF0aW9uYWxpdHkiOiJDb3VudHJ5Iiwib2NjdXBhdGlvbiI6IkRldmVsb3BlciIsImlzV2VsY29tZSI6ZmFsc2UsImlhdCI6MTcwODQyODMzNCwiZXhwIjoxNzA4NDMxOTM0fQ.axKxFIw9hP1LiQspVxUIzsMDIlBz-U6zuk7gWI9Atdg


### get 1 user by id

GET http://localhost:4100/users/4dc65ee2-f7ae-422e-9373-964241733068
Content-Type: application/json

### update user

PUT http://localhost:4100/users/update/2421bdb1-cd15-4bd8-86b6-170c4c8dfd81
Content-Type: application/json

{
 "name": "Jack issa",
  "email": "jack.doe@example.com",
  "nationalId": "12384256789",
  "phoneNumber": "1203-4536-7890",
  "location": "City, Country",
  "gender": "Male",
  "nationality": "Country",
  "occupation": "Developer",
  "dateOfBirth": "1990-01-01T00:00:00.000Z"
}

### delete a user
DELETE http://localhost:4100/users/delete/4dc65ee2-f7ae-422e-9373-964241733068